name: FoodFacts

description: A barcode scanning app, that shows the nutrition of food products.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_admob: ^0.10.0+2
  firebase_analytics: ^6.0.2
  firebase_auth: ^0.18.1+1 
  firebase_core: ^0.5.0+1
  firebase_crashlytics: ^0.2.1+1
  firebase_performance: ^0.4.0+2

  google_sign_in: ^4.5.4

  cupertino_icons: ^1.0.0

  openfoodfacts: ^0.3.12+1

  flutter_barcode_scanner: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
      - assets/food_facts_logo.png
      - assets/google_logo.png

